kind = "api"
previewPath = "/api"
title = "NXT Discord Bot"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 3000
name = "NXT Discord Bot"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.run]
args = ["node", "artifacts/discord-bot/src/index.js"]

[services.production.run.env]
PORT = "3000"
NODE_ENV = "production"

[services.production.health.startup]
path = "/"
